
[uwsgi]
; uwsgi-socket    = /tmp/uwsgi.sock
socket=:5000
; chdir           = ./
chmod-socket    = 777
callable        = app
plugin          = python3

wsgi-file       = app/__init__.py
; 加上以这这行代码支持nginx配置带前缀的location
route-run = fixpathinfo:

; ; 支持nignx配置location前缀为'/myoss'
; mount=/myoss=app/__init__.py
; manage-script-name=true

buffer-size     = 65535
processes       = %(%k * 2)
threads         = %(%k * 10)
disable-logging = true

; 这里的processes和threads，分别是开启的进程数和线程数，而%k是魔数变量，代表CPU核数，
; 如果我们是双核CPU，那这里的processes和threads分别为4和40，即有4个进程，每个进程有40个线程。

